os:
- linux
language: ruby
install: bundle install --jobs=3 --retry=3
rvm:
  - 2.2.0
  - 1.9.5
before_install:
- sudo apt-get update
- gem update --system
- gem update
- gem --version
before_script:
- bundle exec rake
notifications:
  email: false
  slack: crmis:WrJjBadZljqSEJqLQonbcAVd
